<?php
/* termos.php — TERMOS DE USO DO CONSTRUCTCOUNT (app + assinaturas).
   Aceite obrigatório ao CRIAR CONTA (register.php grava users.terms_accepted_at/version).
   Cláusula central: takeoff/IA são ESTIMATIVAS que o usuário CONFERE — a
   responsabilidade final do orçamento é de quem o emite. Versão datada abaixo. */
require __DIR__ . '/lib/layout.php';

const TERMS_APP_VERSION = '2026-06-12';
$L = lang();
$i = $L === 'en' ? 1 : ($L === 'es' ? 2 : 0);

/* [pt_título, en, es, [pt_texto, en, es]] */
$S = [
  ['1. O serviço', '1. The service', '1. El servicio',
   ['O ConstructCount é um software de takeoff e orçamento de construção com IA (app para Windows e versão no navegador), da M2PB, vendido por assinatura em pacotes (ofícios, combos e add-ons). Cada pacote libera os módulos correspondentes na sua licença.',
    'ConstructCount is an AI construction takeoff and estimating software (Windows app and browser version) by M2PB, sold by subscription in packages (trades, combos and add-ons). Each package unlocks the matching modules on your license.',
    'ConstructCount es un software de cómputo y presupuesto de construcción con IA (app para Windows y versión web) de M2PB, vendido por suscripción en paquetes (oficios, combos y add-ons). Cada paquete desbloquea los módulos correspondientes en tu licencia.']],
  ['2. Estimativas e conferência (IMPORTANTE)', '2. Estimates and review (IMPORTANT)', '2. Estimaciones y revisión (IMPORTANTE)',
   ['As leituras de IA, medições, quantidades e preços gerados pelo sistema são AUXILIARES e ESTIMATIVAS. O app marca itens lidos pela IA para a SUA conferência (⚠️) — confira tudo antes de usar. Orçamentos, propostas e pedidos emitidos com o sistema são de responsabilidade EXCLUSIVA do usuário que os emite. O ConstructCount não responde por erros de medição, quantidade, preço ou por perdas decorrentes de orçamentos enviados sem conferência.',
    'AI readings, measurements, quantities and prices generated by the system are AIDS and ESTIMATES. The app flags AI-read items for YOUR review (⚠️) — verify everything before using it. Quotes, proposals and orders issued with the system are the EXCLUSIVE responsibility of the user who issues them. ConstructCount is not liable for measurement, quantity or price errors, or for losses arising from estimates sent without review.',
    'Las lecturas de IA, mediciones, cantidades y precios generados por el sistema son AUXILIARES y ESTIMACIONES. La app marca lo leído por la IA para TU revisión (⚠️) — verifica todo antes de usarlo. Los presupuestos, propuestas y pedidos emitidos con el sistema son responsabilidad EXCLUSIVA del usuario que los emite. ConstructCount no responde por errores de medición, cantidad o precio, ni por pérdidas derivadas de presupuestos enviados sin revisión.']],
  ['3. Conta, licença e dispositivos', '3. Account, license and devices', '3. Cuenta, licencia y dispositivos',
   ['A conta exige dados verdadeiros; o e-mail é o canal oficial. A chave de licença é pessoal e intransferível, limitada ao número de dispositivos do plano. É proibido compartilhar, revender ou burlar a licença e os bloqueios de pacote. O teste grátis de 7 dias (sem cartão) é limitado a 1 por conta.',
    'The account requires truthful information; e-mail is the official channel. The license key is personal and non-transferable, limited to the plan\'s device count. Sharing, reselling or circumventing the license and package locks is prohibited. The 7-day free trial (no card) is limited to 1 per account.',
    'La cuenta exige datos verdaderos; el e-mail es el canal oficial. La clave de licencia es personal e intransferible, limitada al número de dispositivos del plan. Está prohibido compartir, revender o eludir la licencia y los bloqueos de paquetes. La prueba gratis de 7 días (sin tarjeta) se limita a 1 por cuenta.']],
  ['4. Pagamento, renovação e cancelamento', '4. Payment, renewal and cancellation', '4. Pago, renovación y cancelación',
   ['Assinaturas renovam automaticamente (mensal/anual) pelo gateway de pagamento, até o cancelamento. O cancelamento vale a partir do fim do período já pago. Pacotes pré-pagos por período fechado (ex.: regiões do Mural por 3/6/12 meses) não renovam e valem até a data contratada. Impostos sobre a assinatura seguem a localidade do cliente. Estornos indevidos podem suspender a licença.',
    'Subscriptions renew automatically (monthly/yearly) through the payment gateway until cancelled. Cancellation takes effect at the end of the paid period. Fixed-period prepaid packages (e.g., Board regions for 3/6/12 months) do not renew and last until the contracted date. Subscription taxes follow the customer\'s location. Improper chargebacks may suspend the license.',
    'Las suscripciones se renuevan automáticamente (mensual/anual) por la pasarela de pago hasta su cancelación. La cancelación rige desde el fin del período pagado. Los paquetes prepagados por período cerrado (p. ej., regiones del Mural por 3/6/12 meses) no se renuevan y valen hasta la fecha contratada. Los impuestos de la suscripción siguen la localidad del cliente. Contracargos indebidos pueden suspender la licencia.']],
  ['5. IA e seus dados', '5. AI and your data', '5. IA y tus datos',
   ['O motor de leitura roda LOCALMENTE no seu computador — suas plantas não saem da sua máquina no fluxo padrão do desktop. Recursos de nuvem OPCIONAIS (leitura de tipos de parede por visão, pesquisa de preços por região, texto de relatórios por IA) enviam ao servidor apenas o necessário, quando você os usa. Trechos de TEXTO de tipos de parede podem ser coletados de forma anônima para melhorar o leitor de todos. Seus projetos, orçamentos e relatórios são SEUS.',
    'The reading engine runs LOCALLY on your computer — your plans do not leave your machine in the standard desktop flow. OPTIONAL cloud features (wall-type vision reading, regional price lookup, AI report text) send the server only what is needed, when you use them. Wall-type TEXT snippets may be collected anonymously to improve the reader for everyone. Your projects, estimates and reports are YOURS.',
    'El motor de lectura corre LOCALMENTE en tu computadora — tus planos no salen de tu máquina en el flujo estándar del escritorio. Las funciones de nube OPCIONALES (lectura de tipos de pared por visión, búsqueda de precios por región, texto de informes por IA) envían al servidor solo lo necesario, cuando las usas. Fragmentos de TEXTO de tipos de pared pueden recopilarse de forma anónima para mejorar el lector de todos. Tus proyectos, presupuestos e informes son TUYOS.']],
  ['6. Mural de projetos', '6. Project board', '6. Mural de proyectos',
   ['O uso do Mural de projetos (publicar obras e dar preço) tem termos próprios, com prazos, multas e regras de exclusão — leia os Termos de uso do Mural.',
    'Using the Project Board (posting jobs and bidding) has its own terms, with deadlines, penalties and deletion rules — read the Board terms of use.',
    'El uso del Mural de proyectos (publicar obras y dar precio) tiene términos propios, con plazos, multas y reglas de eliminación — lee los Términos de uso del Mural.']],
  ['7. Propriedade intelectual', '7. Intellectual property', '7. Propiedad intelectual',
   ['O software, a marca e o site pertencem à M2PB. A assinatura dá direito de USO, não de propriedade. É proibida a engenharia reversa, a cópia e a redistribuição do software.',
    'The software, brand and website belong to M2PB. The subscription grants a right of USE, not ownership. Reverse engineering, copying and redistribution of the software are prohibited.',
    'El software, la marca y el sitio pertenecen a M2PB. La suscripción otorga derecho de USO, no de propiedad. Quedan prohibidas la ingeniería inversa, la copia y la redistribución del software.']],
  ['8. Disponibilidade e atualizações', '8. Availability and updates', '8. Disponibilidad y actualizaciones',
   ['O app recebe atualizações (interface remota e versões do instalador). Serviços online podem ter manutenção e indisponibilidade eventual; o serviço é fornecido "como está".',
    'The app receives updates (remote interface and installer releases). Online services may have maintenance and occasional downtime; the service is provided "as is".',
    'La app recibe actualizaciones (interfaz remota y versiones del instalador). Los servicios en línea pueden tener mantenimiento e indisponibilidad eventual; el servicio se ofrece "tal cual".']],
  ['9. Responsabilidade', '9. Liability', '9. Responsabilidad',
   ['Na máxima extensão permitida em lei, a responsabilidade total do ConstructCount/M2PB limita-se aos valores pagos pelo usuário nos últimos 12 meses. Em nenhum caso respondemos por lucros cessantes ou danos indiretos decorrentes do uso do sistema.',
    'To the maximum extent permitted by law, the total liability of ConstructCount/M2PB is limited to the amounts paid by the user in the last 12 months. In no event are we liable for lost profits or indirect damages arising from use of the system.',
    'En la máxima medida permitida por la ley, la responsabilidad total de ConstructCount/M2PB se limita a los montos pagados por el usuario en los últimos 12 meses. En ningún caso respondemos por lucro cesante o daños indirectos derivados del uso del sistema.']],
  ['10. Alterações', '10. Changes', '10. Cambios',
   ['Estes termos podem ser atualizados; a versão vigente fica nesta página com a data. O uso do sistema após a publicação de mudanças vale como aceite. Versão: {ver}.',
    'These terms may be updated; the current version lives on this page with its date. Using the system after changes are posted constitutes acceptance. Version: {ver}.',
    'Estos términos pueden actualizarse; la versión vigente queda en esta página con su fecha. Usar el sistema después de publicarse cambios constituye aceptación. Versión: {ver}.']],
];

layout_top(t('terms_app_title'));
?>
<div class="card" style="max-width:820px;margin:0 auto">
  <h2>📜 <?= h(t('terms_app_title')) ?></h2>
  <p class="muted"><?= h(t('terms_app_sub')) ?> · <?= h(TERMS_APP_VERSION) ?></p>
  <?php foreach ($S as $sec): ?>
    <h3 style="margin:18px 0 6px"><?= h($sec[$i]) ?></h3>
    <p style="margin:0;font-size:13.5px;line-height:1.65"><?= h(str_replace('{ver}', TERMS_APP_VERSION, $sec[3][$i])) ?></p>
    <?php if (strpos($sec[0], '6.') === 0): ?><p style="margin:6px 0 0;font-size:13px"><a href="<?= h(url('termos-mural.php')) ?>">📋 <?= h(t('terms_title')) ?> »</a></p><?php endif; ?>
  <?php endforeach; ?>
  <p style="margin-top:20px"><a class="btn ghost" href="<?= h(url('index.php')) ?>">« ConstructCount</a></p>
</div>
<?php layout_bottom(); ?>
